# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23a2d42d96950d6c25f3f5a7b3ea801c5a56ad6689233ce953f29294b0313270f61e55b26065134b63afd01b53016831d12aab512e9a9c70057309365d4ff966

test:
  secret_key_base: 810beac1ff5b30a2fd782b71f4f73820c44a9c5e456ff75e580dae62546fec21033b4376676e6e25e9949616fab31903a2e6afc7607c4b075fae04ede0e805e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
